version: "3.7"

services: 
    webserver:
        depends_on:
            - db
        image: zacsketches/consul-example-webserver
        ports: 
            - "8080:8080"
        networks: 
            - example

    db:
        image: mongo
        ports:
            - "27017:27017"
        networks: 
            - example

networks: 
    example:
